using System.Collections.Generic;
using System.Globalization;
using System;

namespace MoonPull.Localization
{
    public interface ILocalizationService
    {
        string CurrentCode { get; }
        IReadOnlyList<string> SupportedCodes { get; }
        event Action LanguageChanged;

        /// <summary>Localized string for <paramref name="key"/>; returns the key itself if missing, so gaps are visible in QA.</summary>
        string Get(string key);

        string Format(string key, params object[] args);

        /// <summary>Formats a number with the current locale's separators (1,250 vs 1.250).</summary>
        string Number(long value);

        string DisplayName(string code);

        void SetLanguage(string code);
    }

    /// <summary>
    /// CSV-backed localization (Resources/Localization/MoonPull_UI.csv, generated by Tools/generate_localization.py).
    /// Chosen over the Unity Localization package because its tables must be authored in the Editor, while this
    /// project is built entirely from source on CI. uGUI Text falls back to the phone's system fonts, so Japanese and
    /// Cyrillic render without shipping font atlases.
    /// </summary>
    public sealed class CsvLocalizationService : ILocalizationService
    {
        public const string ResourcePath = "Localization/MoonPull_UI";

        private static readonly string[] Codes = { "en", "tr", "es", "pt-BR", "de", "fr", "ru", "ja" };

        private static readonly Dictionary<string, string> Names = new Dictionary<string, string>
        {
            { "en", "English" },
            { "tr", "Türkçe" },
            { "es", "Español" },
            { "pt-BR", "Português (Brasil)" },
            { "de", "Deutsch" },
            { "fr", "Français" },
            { "ru", "Русский" },
            { "ja", "日本語" }
        };

        private readonly Dictionary<string, string[]> table = new Dictionary<string, string[]>(256);
        private int column;
        private CultureInfo culture = CultureInfo.InvariantCulture;

        public event Action LanguageChanged;

        public string CurrentCode { get; private set; } = "en";

        public IReadOnlyList<string> SupportedCodes => Codes;

        /// <summary>Loads the table and applies the saved language (empty = device language).</summary>
        public void Initialize(string savedCode)
        {
            var asset = UnityEngine.Resources.Load<UnityEngine.TextAsset>(ResourcePath);
            if (asset != null)
            {
                Load(asset.text);
            }
            else
            {
                UnityEngine.Debug.LogError("[Localization] " + ResourcePath + " missing; UI will show keys.");
            }

            Apply(string.IsNullOrEmpty(savedCode) ? DeviceCode() : savedCode);
        }

        /// <summary>Parses the CSV. Public for tests.</summary>
        public void Load(string csv)
        {
            table.Clear();
            List<List<string>> rows = CsvParser.Parse(csv);
            for (int r = 1; r < rows.Count; r++)
            {
                List<string> row = rows[r];
                if (row.Count < 2 || string.IsNullOrEmpty(row[0]))
                {
                    continue;
                }

                var values = new string[Codes.Length];
                for (int c = 0; c < Codes.Length; c++)
                {
                    values[c] = c + 1 < row.Count ? row[c + 1] : string.Empty;
                }

                table[row[0]] = values;
            }
        }

        public string Get(string key)
        {
            if (key != null && table.TryGetValue(key, out string[] values))
            {
                string value = values[column];
                return string.IsNullOrEmpty(value) ? values[0] : value;
            }

            return key;
        }

        public string Format(string key, params object[] args)
        {
            try
            {
                return string.Format(culture, Get(key), args);
            }
            catch (FormatException)
            {
                return Get(key);
            }
        }

        public string Number(long value) => value.ToString("N0", culture);

        public string DisplayName(string code) => Names.TryGetValue(code, out string name) ? name : code;

        public void SetLanguage(string code)
        {
            if (code == CurrentCode)
            {
                return;
            }

            Apply(code);
            LanguageChanged?.Invoke();
        }

        private void Apply(string code)
        {
            int index = Array.IndexOf(Codes, code);
            if (index < 0)
            {
                index = 0;
            }

            column = index;
            CurrentCode = Codes[index];
            try
            {
                culture = new CultureInfo(CurrentCode);
            }
            catch (CultureNotFoundException)
            {
                culture = CultureInfo.InvariantCulture;
            }
        }

        private static string DeviceCode()
        {
            switch (UnityEngine.Application.systemLanguage)
            {
                case UnityEngine.SystemLanguage.Turkish: return "tr";
                case UnityEngine.SystemLanguage.Spanish: return "es";
                case UnityEngine.SystemLanguage.Portuguese: return "pt-BR";
                case UnityEngine.SystemLanguage.German: return "de";
                case UnityEngine.SystemLanguage.French: return "fr";
                case UnityEngine.SystemLanguage.Russian: return "ru";
                case UnityEngine.SystemLanguage.Japanese: return "ja";
                default: return "en";
            }
        }
    }

    /// <summary>RFC 4180 CSV parser (quoted fields, escaped quotes, newlines inside quotes).</summary>
    public static class CsvParser
    {
        public static List<List<string>> Parse(string text)
        {
            var rows = new List<List<string>>();
            var row = new List<string>();
            var field = new System.Text.StringBuilder();
            bool quoted = false;
            for (int i = 0; i < text.Length; i++)
            {
                char c = text[i];
                if (quoted)
                {
                    if (c == '"')
                    {
                        if (i + 1 < text.Length && text[i + 1] == '"')
                        {
                            field.Append('"');
                            i++;
                        }
                        else
                        {
                            quoted = false;
                        }
                    }
                    else
                    {
                        field.Append(c);
                    }
                }
                else if (c == '"')
                {
                    quoted = true;
                }
                else if (c == ',')
                {
                    row.Add(field.ToString());
                    field.Clear();
                }
                else if (c == '\n' || c == '\r')
                {
                    if (c == '\r' && i + 1 < text.Length && text[i + 1] == '\n')
                    {
                        i++;
                    }

                    row.Add(field.ToString());
                    field.Clear();
                    rows.Add(row);
                    row = new List<string>();
                }
                else if (c != '\uFEFF')
                {
                    field.Append(c);
                }
            }

            if (field.Length > 0 || row.Count > 0)
            {
                row.Add(field.ToString());
                rows.Add(row);
            }

            return rows;
        }
    }
}
